services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    container_name: url_shortener_app
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./application.yaml:/app/config/application.yaml
    depends_on:
      - mongodb

volumes:
  mongo_data: